// <auto-generated />
using Cadastro__.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cadastro__.Migrations
{
    [DbContext(typeof(aplicationDatabase))]
    [Migration("20230428004253_CreateClientDatabase")]
    partial class CreateClientDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cadastro__.Models.clienteModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cadData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("cadStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("cpfcnpj")
                        .HasColumnType("int");

                    b.Property<int>("dataNasc")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("inscEstadual")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.Property<int>("tipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
